const movieData = [
  {
    id: 1,
    title: "Mystic Shadows: The Awakening",
    genres: ["Fantasy", "Adventure"],
    likes: "843.7K",
    rating: "8.5",
    votes: "67.3K",
    promoted: true,
    imageUrl: "/api/placeholder/256/384",
    description:
      "A young wizard discovers her powers in a world where magic is forbidden.",
  },
  {
    id: 2,
    title: "Chrome Warriors 2185",
    genres: ["Sci-Fi", "Action"],
    likes: "692.1K",
    rating: "8.8",
    votes: "55.9K",
    promoted: true,
    imageUrl: "/api/placeholder/256/384",
    description:
      "In a dystopian future, rebel cyborgs fight for humanity's survival.",
  },
  {
    id: 3,
    title: "The Last Laughter",
    genres: ["Comedy", "Drama"],
    likes: "551.8K",
    rating: "7.9",
    votes: "42.3K",
    promoted: false,
    imageUrl: "/api/placeholder/256/384",
    description: "A retired comedian returns to the stage one last time.",
  },
  {
    id: 4,
    title: "Whispers in the Wind",
    genres: ["Romance", "Mystery"],
    likes: "432.5K",
    rating: "8.2",
    votes: "38.7K",
    promoted: false,
    imageUrl: "/api/placeholder/256/384",
    description:
      "Love blooms in a small coastal town haunted by ancient secrets.",
  },
  {
    id: 5,
    title: "Neon Nights: Underground",
    genres: ["Action", "Crime", "Thriller"],
    likes: "723.4K",
    rating: "8.7",
    votes: "59.2K",
    promoted: true,
    imageUrl: "/api/placeholder/256/384",
    description:
      "A street racer gets entangled in a dangerous criminal conspiracy.",
  },
  {
    id: 6,
    title: "The Silent Echo",
    genres: ["Horror", "Psychological"],
    likes: "321.9K",
    rating: "7.5",
    votes: "31.4K",
    promoted: false,
    imageUrl: "/api/placeholder/256/384",
    description:
      "A psychologist uncovers disturbing patterns in their patients' nightmares.",
  },
  {
    id: 7,
    title: "Family Ties & Lies",
    genres: ["Drama", "Family"],
    likes: "445.2K",
    rating: "8.4",
    votes: "41.8K",
    promoted: false,
    imageUrl: "/api/placeholder/256/384",
    description:
      "Three generations confront their past during a reunion weekend.",
  },
  {
    id: 8,
    title: "Beyond the Horizon",
    genres: ["Adventure", "Documentary"],
    likes: "287.6K",
    rating: "9.1",
    votes: "28.5K",
    promoted: false,
    imageUrl: "/api/placeholder/256/384",
    description: "Explorers journey to Earth's last unmapped frontiers.",
  },
  {
    id: 9,
    title: "Digital Dreams",
    genres: ["Sci-Fi", "Romance"],
    likes: "534.8K",
    rating: "8.3",
    votes: "47.6K",
    promoted: true,
    imageUrl: "/api/placeholder/256/384",
    description:
      "Virtual reality dating leads to unexpected real-world consequences.",
  },
  {
    id: 10,
    title: "The Great Heist",
    genres: ["Action", "Comedy", "Crime"],
    likes: "678.3K",
    rating: "8.6",
    votes: "52.1K",
    promoted: false,
    imageUrl: "/api/placeholder/256/384",
    description:
      "A team of misfit thieves attempts the impossible: stealing the unstealable.",
  },
];

export default movieData;
